name: Deploy Databricks Bundle

on:
  push:
    branches:
      - develop
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      DATABIRCKS_AUTH_TYPE: github-oidc
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      DATABRICKS_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      DATABRICKS_BUNDLE_ENGINE: direct

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: |
          curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh
          databricks --version

      - name: Validate bundle
        working-directory: DAB/yelpaz_databricks
        run: |
          databricks bundle validate

      - name: Deploy to DEV
        if: github.ref == 'refs/heads/develop'
        working-directory: DAB/yelpaz_databricks
        run: |
          databricks bundle deploy -t dev

      - name: Deploy to PROD
        if: github.ref == 'refs/heads/main'
        working-directory: DAB/yelpaz_databricks
        run: |
          databricks bundle deploy -t prod